camera_name: usb_cam_1
image_topic: /usb_cam_1/image_raw
has_finish_line: true
merge_zones:
- x_min: 976
  x_max: 1116
  y_min: 201
  y_max: 811
fuel_zone:
  x_min: 467
  x_max: 891
  y_min: 128
  y_max: 279
charge_gate_zone:
  x_min: 54
  x_max: 258
  y_min: 201
  y_max: 405
ignore_zones:
- x_min: 932
  x_max: 1022
  y_min: 163
  y_max: 240
- x_min: 425
  x_max: 511
  y_min: 154
  y_max: 232
- x_min: 841
  x_max: 930
  y_min: 141
  y_max: 217
finish_line:
  x: 679
  direction: left_to_right
