camera_name: usb_cam_1
image_topic: /usb_cam_1/image_raw
has_finish_line: true
merge_zones:
- x_min: 937
  x_max: 1077
  y_min: 154
  y_max: 528
fuel_zone:
  x_min: 413
  x_max: 832
  y_min: 136
  y_max: 224
charge_gate_zone:
  x_min: 79
  x_max: 205
  y_min: 154
  y_max: 279
ignore_zones:
- x_min: 893
  x_max: 983
  y_min: 116
  y_max: 194
- x_min: 789
  x_max: 874
  y_min: 103
  y_max: 178
- x_min: 370
  x_max: 457
  y_min: 100
  y_max: 174
finish_line:
  x: 622
  direction: left_to_right
